# redimp/netshell bashrc

if [ $(tput colors) -ge 8 ]; then
  export PS1="\w \[\033[01;34m\]❯\[\033[00m\]❯ "
else
  export PS1="\w ❯❯ "
fi

cheatsh() {
    curl -s "https://cheat.sh/$1"
}

if ! test -f /tmp/greeting.$$; then
  cat /etc/motd
  touch /tmp/greeting.$$
fi
